name: Go

on:
  push:
    branches: [ "stable" ]

    tags:
      - 'v*' 
  pull_request:
    branches: [ "stable" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Pipery Go CI
      uses: pipery-dev/golang-ci@v1
      with:

        go_version: '1.26.4'

        skip_test: true
        skip_packaging: true
        
        github_token: ${{ secrets.GITHUB_TOKEN }}
